### ISSUE TITLE
Output portion of meta-model

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/analysis-results-standard#10]
For this PBI the dev team will deliver, using the new technology choices (xml, json, linkml, whatever is correct), the Output portion of the metamodel.  

We know that other portions of the metamodel (like Display) will have dependencies on Output, but we will construct those ties with Output when we deliver those depending items.  Unless something else comes up during the Sprint Output will be delivered without dependencies on anything else.

If dependencies against Output are obvious, we can create placeholders for those depending items.

**Comment by drewcdisc** [comment]
Richard, you might want to use a comment like this one to track the tasks that you decide will help you organize your work in fulling this PBI.  For instance:

- [ ] Spin fizzlebot with the fobcrank
- [ ] Push the doohickey using the grizbanger
- [ ] Fill the baztank with the foobar contents

You probably want to change those. :)

**Comment by ASL-rmarshall** [comment]
@bhavinbusa I have posted the following files for you to take a look at:
- [ars_ldm.yaml](https://github.dev/cdisc-org/analysis-results-standard/blob/411be8852d512cb223b83c3c5d9719b26aea2a2b/model/ars_ldm.yaml#L1): the beginnings of the logical data model represented using LinkML.
- [ars_ldm.svg](https://github.dev/cdisc-org/analysis-results-standard/blob/411be8852d512cb223b83c3c5d9719b26aea2a2b/model/ars_ldm.svg#L1): an SVG pictorial representation of the model.
- [ARS.cmap](https://github.dev/cdisc-org/analysis-results-standard/blob/411be8852d512cb223b83c3c5d9719b26aea2a2b/workfiles/ARS.cmap): the updated cmap file that I have been using for whiteboarding (needs [CmapTools](https://cmap.ihmc.us/products/) to view).
- [lopo.yaml](https://github.dev/cdisc-org/analysis-results-standard/blob/411be8852d512cb223b83c3c5d9719b26aea2a2b/workfiles/examples/lopo.yaml#L1): an example showing details of the 3 example outputs represented in YAML format using the model.
FYI @drewcdisc @chowsanthony @lexjansen

**Comment by lexjansen** [comment]
A few minor comments on the model.
- Several names (not all) start with fragments like "listof" or "listed". Could you for example just call them plannedOutputs instead of listOfPlannedOutputs, and output instead of listedOutput. It's maybe just a matter of taste, but it is not a bad thing to stay closer to names that end users will use.
- I would love to see an example with where the outputs are nested.

**Comment by ASL-rmarshall** [comment]
@lexjansen 
I have added a new, more complex example ([lopo2.yaml](https://github.dev/cdisc-org/analysis-results-standard/blob/497c7207c6bd9b963a7017eda884716aa965c287/workfiles/examples/lopo2.yaml#L1)), which represents the following nested list structure:

CDISC 360 Pilot 1 CSR
- 1 Safety
  - 1.1 Standard Demographics Table [T14201-DEMOG]
  - 1.2 AE Summary Table [T14301-AE-SUMM]
  - 1.3 Vital Signs Change from Baseline Table [T14303-VITALS-CHGBL]
  - 1.4 Drug Induced Liver Injury (DILI)
    - 1.4.1 Liver Function Tests Change from Baseline [T140401-LFT-CHGBL]
    - 1.4.2 Liver Function Test AE Summary [T140402-LFT-AE-SUMM]
- 2 Efficacy
  - 2.1 Change from Baseline in Extent of Disease [T14303-EOD-CHGBL]

**Comment by bhavinbusa** [comment]
"Should Output have a Name in addition to DisplayID and File Name? This is the text that would be displayed in the List of Outputs, so name is assigned for each list entry, not for the object itself" 
Answer: The display name element is part of the "Display" metadata table. This element is defined as "Display name which uniquely identifies the display in the report (e.g. Table or Figure number)". However, you bring up a good point. There could be a use case where there could be multiple displays within an output. For e.g. efficacy result analyzed across multiple co-variates could have multiple tables (e.g. 14.2.1a, 14.2.1b and 14.2.1c which could be part of the output 14.2.1). Can we discuss this scenario during our call? I want to make sure we think through this a bit as a team - also discuss this with the wider ARS team.

**Comment by bhavinbusa** [comment]
Question: "Is "Group" a group of analyses or a group of displays?  If both are needed, what correspondence is there betwee each listed output and each listed analysis description?"
BB Response: It is group of analyses. The output could be a group of displays.

**Comment by bhavinbusa** [comment]
Question: On Order, is it an execution order or list order? 
BB Response: Good question. Can it be for both? or should we think of having 2 separate elements?

**Comment by bhavinbusa** [comment]
We should discuss example of the sub-list tomorrow. Not sure what you have in mind for this branch.

**Comment by bhavinbusa** [comment]
Question: On Version....Output version or File version?
BB Response: We were thinking this to be Output version which can also be used for the file version. But if you run the same version of the output more than once, the file version could be out of sync. Do we need to care about the file version? Let's discuss this with the wider team. Thxs
